### ISSUE TITLE
Filter  interface design

### ISSUE THREAD

**Issue by itsjamie** [ingest/manifest#6]
When implementing the checks for `EXT-X-VERSION` compatibility in the PR #5, https://github.com/ingest/manifest/pull/5#issuecomment-311816612 was mentioned. It seems like a very simple but powerful way to implement changes for repackaging manifest at the edge.

I was thinking of how the design would work if it was implementing in this package, and was considering:

```go
package hls

type Filter interface {
    Filter(*MediaPlaylist) error
}
```

Then, implementation of a similar method as to outlined in the comment would be very close...

```go
type ConsistentKeys struct{}

// Filter implements MediaFilter interface
func (f ConsistentKeys) Filter(pls *MediaPlaylist) error {
    var lastKey *m3u8.Key
    for i := uint(0); i < pls.Count(); i++ {
        if pls.Segments[i] == nil {
            break
        }
        if pls.Segments[i].Key == nil {
            pls.Segments[i].Key = lastKey
        }
        lastKey = pls.Segments[i].Key
    }
    return nil
}
```

If the filter was intended to be used with other data these fields could be added to the struct and used in the implementation of the interface.

```go
type UAPackager struct {
    UA string
}

func (u *UAPackager) Filter(pls *MediaPlaylist) error {
   switch u.UA {
   case "Roku 1", "Roku 2": // ( if only it was this easy :) )
       // ensure no 5.1 channels are included to not blow up old rokus without receiver
   }

   return nil
}
```

@tainacleal @bradleyfalzon Thoughts?

**Comment by bradleyfalzon** [comment]
This method worked well enough for us, and it's a better idea to remove the http.ResponseWriter / http.Request, we shouldn't have coupled those.

We also named it filter for lack of better term, I'm not sure if you wanted to rename it? I was thinking `Formatter` but that's not quite there either. Just a thought, it's not a big thing.

The other thought, is we initialised the filters with:

```go
319     stream.AddMediaFilter(ConsistentKeys{})
320     stream.AddMediaFilter(LimitLiveFirstPlayChunks{Limit: 3, PlayStartMSN: stream.PlayStartMSN})
321     w = stream.RunMediaFilters(content, w, r)
322
323     fmt.Fprint(w, content.String())
```

I'm not sure if it's the best method to do it, it worked for us though.
